# Based on https://github.com/pydantic/pydantic/blob/main/.github/actions/core-build-pgo-wheel/action.yml

name: "lava-sh/build-pgo-wheel"
description: "Builds a PGO-optimized Python wheel"
author: "chirizxc"

branding:
  icon: "code"
  color: "purple"

inputs:
  # Rust
  target:
    description: "Rust target to build the wheel for"
    required: true

  rust-toolchain:
    description: "Rust toolchain to use (via dtolnay/rust-toolchain)"
    required: true

  # maturin
  maturin-build-args:
    description: "Additional arguments to pass to maturin build"
    required: false
    default: ""

  maturin-sccache:
    description: "Whether to use sccache"
    required: false
    default: ${{ github.event_name == 'pull_request' }}

  rustflags:
    description: "Additional RUSTFLAGS"
    required: false
    default: ""

  working-directory:
    description: "Working directory to run the action in"
    required: false
    default: "."

  pgo-training-command:
    description: "Command to run PGO training"
    required: true

  wheels-wheels-output-directory:
    description: "Directory to output the built wheel"
    required: false
    default: "dist"
  
outputs:
  wheel:
    description: "Path to the built wheel"
    value: ${{ steps.find_wheel.outputs.path }}

runs:
  using: composite
  steps:
    - name: "Rust Cache"
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      if: github.event_name == 'pull_request'
      with:
        lookup-only: false # zizmor: ignore[cache-poisoning]

    - name: "Install Rust ${{ inputs.rust-toolchain }} + llvm-tools-preview"
      uses: dtolnay/rust-toolchain@master # zizmor: ignore[unpinned-uses]
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        components: llvm-tools-preview

    - name: "Install uv"
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: false

    - name: "📊 Phase 1/4: Building instrumented wheel"
      uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
      with:
        working-directory: ${{ inputs.working-directory }}
        #
        target: ${{ inputs.target }}
        rust-toolchain: ${{ inputs.rust-toolchain }}
        sccache: ${{ inputs.maturin-sccache }}
        manylinux: auto
        docker-options: -e CI -e RUSTFLAGS
        args: >-
          --release
          --out initial-wheel
          --interpreter ${{ inputs.python-interpreter }}
          ${{ inputs.maturin-build-args }}
          --compatibility pypi
      env:
        RUSTFLAGS: >-
          -Cprofile-generate=${{ github.workspace }}/profdata
          ${{ inputs.rustflags }}

    - name: "🔬 Phase 2/4: Generate PGO data"
      working-directory: ${{ inputs.working-directory }}
      env:
        FORCE_COLOR: "1"
        CARGO_TERM_COLOR: always
        INPUTS_TARGET: ${{ inputs.target }}
        INPUTS_PYTHON_INTERPRETER: ${{ inputs.python-interpreter }}
        INPUTS_WORKING_DIRECTORY: ${{ inputs.working-directory }}
        INPUTS_PGO_TRAINING_COMMAND: ${{ inputs.pgo-training-command }}
      shell: bash
      run: python "$GITHUB_ACTION_PATH/pgo.py"

    - name: "🧬 Phase 3/4: Merging profile data"
      shell: pwsh
      env:
        LLVM_PROFDATA: ${{ env.LLVM_PROFDATA }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        & $env:LLVM_PROFDATA merge `
          -o "$env:GITHUB_WORKSPACE/merged.profdata" `
          "$env:GITHUB_WORKSPACE/profdata"

    - name: "⚡ Phase 4/4: Building PGO-optimized wheel"
      uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
      with:
        working-directory: ${{ inputs.working-directory }}
        #
        target: ${{ inputs.target }}
        rust-toolchain: ${{ inputs.rust-toolchain }}
        sccache: ${{ inputs.maturin-sccache }}
        manylinux: auto
        docker-options: -e CI -e RUSTFLAGS
        args: >-
          --release
          --out ${{ inputs.wheels-output-directory }}
          --interpreter ${{ inputs.python-interpreter }}
          ${{ inputs.maturin-build-args }}
          --compatibility pypi
      env:
        RUSTFLAGS: >-
          -Cprofile-use=${{ github.workspace }}/merged.profdata
          ${{ inputs.rustflags }}

    - name: "Show built wheels"
      id: find_wheel
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "📦 Found wheels:"
        for wheel in "${{ inputs.wheels-output-directory }}"/*.whl; do
          echo "  • $(basename "$wheel")"
        done
      
        {
          echo "path<<EOF"
          printf '%s\n' "${{ inputs.wheels-output-directory }}"/*.whl
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
